-- Only safe to run once no ride is sitting in PENDING_ADMIN_ASSIGNMENT.
ALTER TABLE rt_rides
  MODIFY status ENUM(
    'REQUESTED','SEARCHING_DRIVER','DRIVER_ASSIGNED','DRIVER_ARRIVING',
    'DRIVER_ARRIVED','RIDE_STARTED','RIDE_IN_PROGRESS','DRIVER_COMPLETED',
    'PAYMENT_PENDING','COMPLETED',
    'CUSTOMER_CANCELLED','DRIVER_CANCELLED','SYSTEM_CANCELLED',
    'NO_DRIVERS_FOUND','PAYMENT_FAILED'
  ) NOT NULL DEFAULT 'REQUESTED';
